version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'digital-book-accounting-database'
    ports:
      - "5430:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=digital-book-accounting'
      - 'POSTGRES_PASSWORD=postgres'