create table branch (
    id int generated by default as identity primary key ,
    address varchar(200) unique not null
);

create table employee (
    id int generated by default as identity primary key ,
    branch_id int references branch(id) ,
    username varchar(100) unique not null ,
    password varchar not null
);

create table person (
    person_id int generated by default as identity primary key ,
    full_name varchar(100) unique not null ,
    born_year int check ( born_year > 1900 ) not null
);

CREATE TABLE BOOK (
    BOOK_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PERSON_ID INT REFERENCES person(person_id) ON DELETE SET NULL,
    NAME VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR (100),
    YEAR INT,
    ATTACHMENT_DATE DATE
);